name: Deploy Log Analyzer

on:
  push:
    branches:
      - main
    paths:
      - 'log_analyzer/app/**'
      - 'log_analyzer/app/Dockerfile'
      - 'log_analyzer/app/terraform/envs/prod/**'
      - 'terraform_modules/**'
      - '.github/workflows/deploy-app.yml'
      - '.github/workflows/deploy-log-analyzer.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app.yml
    with:
      app_name: log-analyzer
      dockerfile: log_analyzer/app/Dockerfile
      terraform_dir: log_analyzer/app/terraform/envs/prod
    secrets: inherit
