name: Docker CI (Welcome)

on:
  pull_request:
    paths:
      - 'welcome-website/app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build welcome-web image
        run: docker build -f welcome-website/app/Dockerfile welcome-website/app
