name: Infrastructure CI (Welcome)

on:
  pull_request:
    paths:
      - 'terraform_modules/**'
      - 'log_analyzer/app/terraform/**'
      - 'welcome-website/terraform/**'

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  plan:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      terraform_dir: welcome-website/terraform/envs/welcome
      checkov_directory: welcome-website/terraform/envs/welcome
      plan_title: Terraform Plan (welcome)
    secrets: inherit
