name: Infrastructure CI (Prod)

on:
  pull_request:
    paths:
      - 'terraform_modules/**'
      - 'log_analyzer/app/terraform/**'
      - 'welcome-website/terraform/**'

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  plan:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      terraform_dir: log_analyzer/app/terraform/envs/prod
      checkov_directory: log_analyzer/app/terraform/envs/prod
      plan_title: Terraform Plan (prod)
    secrets: inherit
